export const tipsDatabase = {
      japanese: [
        { principle: "Hydration is key. J-Beauty involves layering multiple lightweight, hydrating products like essences and lotions.", ingredient: "Green Tea (antioxidant), Rice Bran (brightening), and Hyaluronic Acid (hydration).", practice: "The 'Double Cleanse' method, using an oil-based cleanser followed by a water-based one to thoroughly remove makeup and impurities.", image: "A collection of minimalist, elegant Japanese skincare bottles with cherry blossoms" },
        { principle: "Simplicity and consistency are paramount. A minimal routine performed daily yields better results than complex, infrequent treatments.", ingredient: "Camellia Oil (Tsubaki) for nourishing hair and skin, and Adzuki Beans for gentle exfoliation.", practice: "Using facial lotions (Keshosui) as hydrating toners, patting them into the skin to boost moisture absorption before serums.", image: "A bottle of camellia oil next to a bowl of adzuki beans" },
      ],
      korean: [
        { principle: "A holistic approach combining skincare, diet, and lifestyle. Consistency is more important than the number of steps.", ingredient: "Snail Mucin (repairing), Centella Asiatica (soothing), and Propolis (anti-bacterial).", practice: "The famous 10-step routine, which includes everything from essences and ampoules to sheet masks, customized to individual skin needs.", image: "A vibrant flatlay of popular K-Beauty products like sheet masks and serums" },
        { principle: "Sun protection is non-negotiable. Daily use of high-SPF sunscreen is the most crucial step for preventing premature aging.", ingredient: "Ginseng for its anti-aging properties, and Birch Juice as a hydrating base in many products.", practice: "The '7 Skin Method' where you apply seven layers of a hydrating toner or essence to achieve intensely hydrated, 'glass skin'.", image: "A sophisticated bottle of Korean sunscreen with a light, elegant texture" },
      ],
      ayurvedic: [
        { principle: "Balancing your specific dosha (Vata, Pitta, Kapha) through diet, lifestyle, and skincare for holistic well-being.", ingredient: "Turmeric (anti-inflammatory), Neem (purifying), and Sandalwood (cooling).", practice: "'Abhyanga,' a self-massage with warm, herb-infused oils to nourish the skin, calm the nervous system, and improve circulation.", image: "Brass bowls filled with colorful Ayurvedic powders like turmeric and sandalwood" },
        { principle: "Beauty comes from within. What you eat directly impacts your skin's health, so a diet of fresh, whole foods is essential.", ingredient: "Amla (Indian Gooseberry), rich in Vitamin C for brightening, and Ashwagandha for reducing stress-related skin issues.", practice: "Using 'Ubtan,' a traditional paste of herbs, flours, and milk/yogurt, as a natural cleanser and exfoliant before special occasions.", image: "A beautiful wooden bowl containing a freshly mixed Ubtan paste with flower petals" },
      ],
      african: [
        { principle: "Using powerful, unrefined ingredients in their natural state to deliver maximum benefits.", ingredient: "Shea Butter (deep moisturizing), African Black Soap (cleansing and clarifying), and Baobab Oil (rich in vitamins).", practice: "Using raw, unrefined Shea Butter as an all-purpose moisturizer for skin, hair, and lips to lock in moisture and protect from the elements.", image: "A rich, golden block of unrefined shea butter next to a bar of African black soap" },
        { principle: "Celebrating the earth's raw gifts. Many remedies are passed down through generations, relying on the potent botanicals of the continent.", ingredient: "Marula Oil for its antioxidant and moisturizing properties, and Rooibos Tea as an anti-inflammatory ingredient in skincare.", practice: "Using clay masks, particularly with Rhassoul clay from Morocco, to detoxify and purify the skin and hair.", image: "A luxurious bottle of Marula oil with marula fruits in the background" },
      ],
      chinese: [
        { principle: "Balancing Yin (cooling) and Yang (warming) energies within the body for overall health, which reflects as radiant skin.", ingredient: "Jade for facial rolling, Goji Berries (antioxidant), and Pearl Powder (brightening).", practice: "'Gua Sha,' a facial massage technique using a flat jade or rose quartz stone to improve circulation and reduce puffiness.", image: "An elegant jade roller and Gua Sha tool on a silk cloth" },
        { principle: "Nourishing the body from the inside out with herbal soups and teas is believed to be the foundation of a beautiful complexion.", ingredient: "White Fungus for hydration, Red Dates for blood circulation, and Ginseng for vitality.", practice: "Using rice water, a byproduct of washing rice, as a hair rinse and facial toner to brighten and soften skin.", image: "A delicate porcelain bowl with white fungus soup and red dates" },
      ],
      american: [
        { principle: "Efficiency and results-driven skincare, often leveraging scientific innovation and powerful active ingredients.", ingredient: "Retinoids (Vitamin A for anti-aging), Vitamin C serums (antioxidants), and Hyaluronic Acid (hydration).", practice: "A streamlined 'cleanse, treat, moisturize, protect' routine, focusing on potent serums to target specific concerns like fine lines or hyperpigmentation.", image: "A modern, clinical-looking lineup of American-brand serums and creams" },
        { principle: "A love for wellness and spa-like experiences at home, using luxurious bath products for relaxation and self-care.", ingredient: "Epsom Salts for muscle relaxation, Oatmeal for soothing baths, and essential oils like Lavender and Eucalyptus.", practice: "Creating elaborate 'bath cocktails' with bath bombs, oils, and soaks to de-stress and nourish the skin.", image: "A luxurious bubble bath with bath bombs, flower petals, and candles" },
      ],
      russian: [
        { principle: "Protecting the skin from extreme weather, using rich, nourishing creams in winter and embracing natural remedies in summer.", ingredient: "Birch Tree Sap (for hydration), Sea Buckthorn Oil (rich in vitamins), and Sour Cream (for masks).", practice: "The 'Banya' (sauna) ritual, which involves high heat to open pores, followed by a 'venik' (a bundle of leafy twigs) massage to boost circulation.", image: "A glamorous collection of Russian makeup, including bold red lipstick and dramatic eyeliner" },
        { principle: "A focus on bold, expressive makeup, particularly emphasizing strong eyes and lips.", ingredient: "Kohl for dramatic eyeliner, vibrant red pigments for lipstick, and shimmering highlighters for a 'snow queen' glow.", practice: "Layering hydrating and protective products to create a barrier against the cold, a practice known as 'winterizing' the skin.", image: "A jar of rich, nourishing face cream next to a branch of sea buckthorn berries" },
      ],
      mediterranean: [
        { principle: "Embracing a diet rich in healthy fats, antioxidants, and vitamins, which translates to glowing skin.", ingredient: "Olive Oil (rich in antioxidants), Honey (antibacterial), and Grapes (resveratrol).", practice: "Using extra virgin olive oil not just in food, but also as a hair mask and skin moisturizer to nourish and protect.", image: "A rustic bottle of olive oil surrounded by fresh olives and rosemary sprigs" },
        { principle: "Utilizing the bounties of the sea, like mineral-rich sea salt and algae, for exfoliation and detoxification.", ingredient: "Sea Salt for scrubs, Rosemary for circulation, and Yogurt for gentle lactic acid exfoliation.", practice: "Creating simple, effective masks using Greek yogurt and honey to soothe, hydrate, and brighten the complexion.", image: "A ceramic bowl of thick Greek yogurt with a drizzle of golden honey" },
      ],
      latin_american: [
        { principle: "Harnessing the power of superfruits and botanicals from the Amazon rainforest and other diverse ecosystems.", ingredient: "Avocado (nourishing), Acai Berry (antioxidant), and Papaya (enzymatic exfoliation).", practice: "Mashing ripe avocado and applying it as a deeply hydrating mask for both hair and face to restore moisture and shine.", image: "A vibrant spread of Latin American fruits like avocado, papaya, and passionfruit" },
        { principle: "A culture of beauty that celebrates vibrant color, confidence, and natural ingredients passed down through generations.", ingredient: "Jojoba Oil, which mimics the skin's natural sebum, and Yerba Mate as a stimulating, antioxidant-rich ingredient.", practice: "Using a mix of raw sugar and honey or oil as a natural body scrub to exfoliate and leave skin incredibly soft.", image: "A colorful flatlay of makeup inspired by Latin culture, featuring bright eyeshadows and bold lipsticks" },
      ]
    };

    export const allTips = [
        { id: "japanese", title: "Japanese Skincare", description: "The art of J-Beauty focuses on prevention, protection, and a 'less is more' philosophy, aiming for 'mochi skin'—soft, plump, and bouncy.", icon: "🌸", image: "A tranquil Japanese garden with cherry blossoms and a stone lantern" },
        { id: "korean", title: "Korean Beauty (K-Beauty)", description: "K-Beauty is known for its innovative products and multi-step routines that prioritize creating a healthy, well-hydrated canvas for a natural, dewy glow.", icon: "💧", image: "The vibrant, neon-lit streets of Seoul at night" },
        { id: "ayurvedic", title: "Ayurvedic Practices", description: "Rooted in ancient Indian wisdom, Ayurveda views beauty as a reflection of inner health, using natural herbs and practices to balance the body's energies (doshas).", icon: "🌿", image: "A serene temple in India with intricate carvings and marigold garlands" },
        { id: "african", title: "African Beauty Secrets", description: "Traditional African beauty rituals utilize potent, natural ingredients sourced from the continent's rich biodiversity to deeply nourish, protect, and heal the skin and hair.", icon: "🌍", image: "A breathtaking sunset over the African savanna with acacia trees" },
        { id: "chinese", title: "Chinese Beauty Rituals", description: "Ancient Chinese beauty practices are deeply rooted in holistic health, Traditional Chinese Medicine (TCM), and balancing the body's internal energies.", icon: "🪭", image: "The majestic Great Wall of China snaking through lush green mountains" },
        { id: "american", title: "American Beauty Trends", description: "American beauty often blends scientific innovation with a love for wellness, creating efficient, results-oriented products and relaxing at-home spa experiences.", icon: "🗽", image: "The iconic skyline of New York City featuring the Statue of Liberty" },
        { id: "russian", title: "Russian Beauty Traditions", description: "Russian beauty secrets are shaped by a need to protect against harsh climates, blending potent natural remedies with glamorous, expressive makeup.", icon: "❄️", image: "The colorful onion domes of St. Basil's Cathedral in Moscow under a snowy sky" },
        { id: "mediterranean", title: "Mediterranean Magic", description: "Inspired by sun-drenched coastlines, this approach uses nutrient-rich ingredients like olive oil and honey for a naturally radiant glow.", icon: "🍋", image: "The stunning blue and white architecture of Santorini, Greece overlooking the sea" },
        { id: "latin_american", title: "Latin American Vibrance", description: "A celebration of color and confidence, leveraging powerful botanicals from diverse ecosystems like the Amazon rainforest.", icon: "🌺", image: "The ancient Mayan ruins of Chichen Itza in Mexico surrounded by jungle" }
    ];